const config = window.client_config || {};
export const {
  API_ROOT_URL, COORD_DECIMALS, CRUISE_ID_PLACEHOLDER, CRUISE_ID_REGEX,
  CUSTOM_CRUISE_NAME, CUSTOM_LOWERING_METADATA_FIELDS, CUSTOM_LOWERING_NAME,
  DATA_DECIMALS, DEFAULT_VESSEL, DISABLE_EVENT_LOGGING, HEADER_TITLE,
  IMAGE_PATH, LOGIN_IMAGE, LOGIN_SCREEN_TXT, LOWERING_ID_PLACEHOLDER,
  LOWERING_ID_REGEX, MAIN_SCREEN_HEADER, MAIN_SCREEN_TXT,
  RECAPTCHA_SITE_KEY, ROOT_PATH, USE_ACCESS_CONTROL, WS_ROOT_URL,
} = config;
export default config;
