version: '3.6'

services:
  sealog-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: whoi/ndsf-sealog-client
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Example of how to map a new client_config.js into the container
      - ./config:/usr/src/app/config:ro

      # Example of how to map a LOGIN_IMAGE into the container
      - ./login.png:/usr/src/app/dist/images/login.png:ro
