name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize
        id: init
        run: |
          # Determine whether to push to Docker Hub based on the event type
          case "${{ github.event_name }}" in
            push)
              DOCKER_PUSH=yes ;;
            *)
              DOCKER_PUSH=no ;;
          esac

          # Map git ref branch or tag name to Docker tag version
          case "${{ github.ref }}" in
            # Do not push upstream branches and tags to Docker Hub
            refs/heads/upstream/*|refs/tags/upstream/*)
              DOCKER_PUSH=no ;;

            # Do not push pull request branches
            refs/pulls/*)
              DOCKER_PUSH=no ;;

            refs/heads/master)
              DOCKER_TAG=latest ;;
            refs/heads/*|refs/tags/*)
              DOCKER_TAG="$(echo "$GITHUB_REF" | cut -d / -f 3- | \
                sed -e 's,/,-,g')" ;;
          esac

          # Record git source and revision
          GIT_SOURCE=$(git config --get remote.origin.url)
          GIT_REVISION=$(git rev-parse HEAD)$(git diff --quiet || echo "-dirty")

          echo ::set-output name=docker_push::$DOCKER_PUSH
          echo ::set-output name=docker_tag::$DOCKER_TAG
          echo ::set-output name=git_source::$GIT_SOURCE
          echo ::set-output name=git_revision::$GIT_REVISION

      - name: Build the Docker image
        run: |
          docker-compose build \
            --build-arg GIT_SOURCE=${{ steps.init.outputs.git_source }} \
            --build-arg GIT_REVISION=${{ steps.init.outputs.git_revision }}

      # There aren't any tests yet...
      # - name: Run test suite
      #   run: docker-compose run sealog-client npm test

      - name: Log into registry
        if: steps.init.outputs.docker_push == 'yes'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to registry
        if: steps.init.outputs.docker_push == 'yes'
        run: |
          IMAGE="whoi/ndsf-sealog-client:${{ steps.init.outputs.docker_tag }}"
          docker tag oceandatatools/sealog-client-vehicle:latest "$IMAGE"
          docker push "$IMAGE"
