name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # For multi-platform builds
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Initialize
        id: init
        run: |
          echo ::set-output name=docker_repo::whoi/$(basename "${{ github.repository }}" | tr A-Z a-z)
          echo ::set-output name=docker_platforms::linux/amd64,linux/arm64

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.init.outputs.docker_repo }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      # Enable Docker layer caching in the GitHub Actions cache.
      #
      # https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-multi-buildx

      - name: Build the Docker image for native
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=registry,ref=${{ steps.init.outputs.docker_repo }}:buildcache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # There aren't any tests yet...
      # - name: Run test suite
      #   run: docker-compose run sealog-client npm test

  docker-push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Initialize
        id: init
        run: |
          echo ::set-output name=docker_repo::whoi/$(basename "${{ github.repository }}" | tr A-Z a-z)
          echo ::set-output name=docker_platforms::linux/amd64,linux/arm64

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.init.outputs.docker_repo }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Restore the cache warmed by the build job
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-multi-buildx

      - name: Push multi-platform image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ steps.init.outputs.docker_platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=registry,ref=${{ steps.init.outputs.docker_repo }}:buildcache,mode=max
